
/// ==================================================================
/// ModuleSharedPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Module.ChatBotInfrastructurePI.Shared
{
  public partial class ModuleSharedPublicFunctions : global::DirRX.Solution.Module.ChatBotInfrastructurePI.Shared.IModuleSharedPublicFunctions
  {
  }
}

/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Module.ChatBotInfrastructurePI.Functions
{
  internal static partial class Module
  {
    private static object GetFunctionsContainer()
    {
      return new global::DirRX.Solution.Module.ChatBotInfrastructurePI.Shared.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("4a2b05a4-6372-44b3-805e-0d8816704359");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}
namespace DirRX.Solution.Module.ChatBotInfrastructurePI.Shared
{
  public partial class ModuleFunctions: global::DirRX.ChatBotInfrastructurePI.Shared.ModuleFunctions
  {

  }
}

/// ==================================================================
/// ModuleHyperlinks.g.cs
/// ==================================================================

namespace DirRX.Solution.Module.ChatBotInfrastructurePI
{
  public static class ChatBotInfrastructurePIClientFunctionHyperlinksExtensions
  {
  }
}

/// ==================================================================
/// ModuleFoldersFilterStates.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Module.ChatBotInfrastructurePI.Shared
{
}

/// ==================================================================
/// ModuleResources.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Module.ChatBotInfrastructurePI.Shared
{
  public class ModuleResources : global::DirRX.ChatBotInfrastructurePI.Shared.ModuleResources, global::DirRX.Solution.Module.ChatBotInfrastructurePI.IModuleResources
  {
  }
}

/// ==================================================================
/// ModuleWidgetParameters.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Module.ChatBotInfrastructurePI.Shared
{  
}
