
/// ==================================================================
/// ChatBotProcessAssignmentState.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{
  public class ChatBotProcessAssignmentState : 
    global::Sungero.CoreEntities.Shared.DatabookEntryState, global::DirRX.ChatBotTask.IChatBotProcessAssignmentState
  {
    public ChatBotProcessAssignmentState(global::DirRX.ChatBotTask.IChatBotProcessAssignment entity) : base(entity) { }

    public new global::DirRX.ChatBotTask.IChatBotProcessAssignmentPropertyStates Properties
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignmentPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::DirRX.ChatBotTask.Shared.ChatBotProcessAssignmentPropertyStates(entity);
    }


    public new global::DirRX.ChatBotTask.IChatBotProcessAssignmentControlStates Controls
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignmentControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::DirRX.ChatBotTask.Shared.ChatBotProcessAssignmentControlStates(entity);
    }

  }


  public class ChatBotProcessAssignmentControlStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryControlStates, global::DirRX.ChatBotTask.IChatBotProcessAssignmentControlStates
  {

    protected internal ChatBotProcessAssignmentControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class ChatBotProcessAssignmentPropertyStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPropertyStates, global::DirRX.ChatBotTask.IChatBotProcessAssignmentPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::System.String> Name 
            {
              get { return this.GetPropertyState<global::System.String>("Name"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Int32?> AssignmentId 
            {
              get { return this.GetPropertyState<global::System.Int32?>("AssignmentId"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::DirRX.ChatBotInfrastructure.IChatBotProcess> ChatBotProcess 
            {
              get { return this.InternalChatBotProcess; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::DirRX.ChatBotInfrastructure.IChatBotProcess> InternalChatBotProcess
            {
              get { return this.GetPropertyState<global::DirRX.ChatBotInfrastructure.IChatBotProcess>("ChatBotProcess"); }
            }


    protected internal ChatBotProcessAssignmentPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

/// ==================================================================
/// ChatBotProcessAssignmentEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{  
    public class ChatBotProcessAssignmentChatBotProcessChangedEventArgs : global::Sungero.Domain.Shared.PropertyChangedEventArgs<global::DirRX.ChatBotInfrastructure.IChatBotProcess>
    {
      public ChatBotProcessAssignmentChatBotProcessChangedEventArgs(global::Sungero.Domain.Shared.IPropertyState<global::DirRX.ChatBotInfrastructure.IChatBotProcess> state, global::DirRX.ChatBotInfrastructure.IChatBotProcess newValue, global::Sungero.Domain.Shared.IEntity entity): base(state, newValue, entity) { }
    }

}

/// ==================================================================
/// ChatBotProcessAssignmentInfo.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{
  public class ChatBotProcessAssignmentInfo : 
    global::Sungero.CoreEntities.Shared.DatabookEntryInfo, global::DirRX.ChatBotTask.IChatBotProcessAssignmentInfo
  {
    public ChatBotProcessAssignmentInfo(global::System.Type entityType) : base(entityType) { }

    public new global::DirRX.ChatBotTask.IChatBotProcessAssignmentPropertiesInfo Properties
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignmentPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::DirRX.ChatBotTask.Shared.ChatBotProcessAssignmentPropertiesInfo(entityType);
    }

  }

  public class ChatBotProcessAssignmentPropertiesInfo : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPropertiesInfo, global::DirRX.ChatBotTask.IChatBotProcessAssignmentPropertiesInfo
  {
        public global::Sungero.Domain.Shared.IStringPropertyInfo Name 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.StringPropertyMetadata>("Name");
             return new global::Sungero.Domain.Shared.StringPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IIntegerPropertyInfo AssignmentId 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.IntegerPropertyMetadata>("AssignmentId");
             return new global::Sungero.Domain.Shared.IntegerPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::DirRX.ChatBotInfrastructure.IChatBotProcessInfo, global::DirRX.ChatBotInfrastructure.IChatBotProcess> ChatBotProcess 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("ChatBotProcess");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::DirRX.ChatBotInfrastructure.IChatBotProcessInfo, global::DirRX.ChatBotInfrastructure.IChatBotProcess>(propertyMetadata);
          }
        }


    protected internal ChatBotProcessAssignmentPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}

/// ==================================================================
/// ChatBotProcessAssignmentHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask
{
  public partial class ChatBotProcessAssignmentSharedHandlers : global::Sungero.CoreEntities.DatabookEntrySharedHandlers
  {
    private global::DirRX.ChatBotTask.IChatBotProcessAssignment _obj
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignment)this.Entity; }
    }
    public virtual void NameChanged(global::Sungero.Domain.Shared.StringPropertyChangedEventArgs e) { }


    public virtual void AssignmentIdChanged(global::Sungero.Domain.Shared.IntegerPropertyChangedEventArgs e) { }


    public virtual void ChatBotProcessChanged(global::DirRX.ChatBotTask.Shared.ChatBotProcessAssignmentChatBotProcessChangedEventArgs e) { }




    public ChatBotProcessAssignmentSharedHandlers(global::DirRX.ChatBotTask.IChatBotProcessAssignment entity) : base(entity)
    {
    }
  }

}

/// ==================================================================
/// ChatBotProcessAssignmentResources.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared.ChatBotProcessAssignment
{
  /// <summary>
  /// Represents ChatBotProcessAssignment resources.
  /// </summary>
  public class ChatBotProcessAssignmentResources : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryResources, global::DirRX.ChatBotTask.ChatBotProcessAssignment.IChatBotProcessAssignmentResources
  {
  }
}

/// ==================================================================
/// ChatBotProcessAssignmentSharedFunctions.g.cs
/// ==================================================================

namespace DirRX.ChatBotTask.Shared
{
  public partial class ChatBotProcessAssignmentFunctions : global::Sungero.CoreEntities.Shared.DatabookEntryFunctions
  {
    private global::DirRX.ChatBotTask.IChatBotProcessAssignment _obj
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignment)this.Entity; }
    }

    public ChatBotProcessAssignmentFunctions(global::DirRX.ChatBotTask.IChatBotProcessAssignment entity) : base(entity) { }
  }
}

/// ==================================================================
/// ChatBotProcessAssignmentFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Functions
{
  internal static class ChatBotProcessAssignment
  {
  }
}

/// ==================================================================
/// ChatBotProcessAssignmentFilterState.g.cs
/// ==================================================================

namespace DirRX.ChatBotTask.Shared.ChatBotProcessAssignment
{
  public class ChatBotProcessAssignmentFilterState : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryFilterState,
    global::DirRX.ChatBotTask.IChatBotProcessAssignmentFilterState
  {


  }
}

/// ==================================================================
/// ChatBotProcessAssignmentSharedPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{
  public class ChatBotProcessAssignmentSharedPublicFunctions : global::DirRX.ChatBotTask.Shared.IChatBotProcessAssignmentSharedPublicFunctions
  {
  }
}
