
/// ==================================================================
/// ChatBotProcessAssignmentEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Client
{ 
  public class ChatBotProcessAssignmentChatBotProcessValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::DirRX.ChatBotInfrastructure.IChatBotProcess>
  {
    public ChatBotProcessAssignmentChatBotProcessValueInputEventArgs(global::DirRX.ChatBotInfrastructure.IChatBotProcess oldValue, global::DirRX.ChatBotInfrastructure.IChatBotProcess newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

}

/// ==================================================================
/// ChatBotProcessAssignmentHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask
{
  public partial class ChatBotProcessAssignmentClientHandlers : global::Sungero.CoreEntities.DatabookEntryClientHandlers
  {
    private global::DirRX.ChatBotTask.IChatBotProcessAssignment _obj
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignment)this.Entity; }
    }

    public virtual void NameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void AssignmentIdValueInput(global::Sungero.Presentation.IntegerValueInputEventArgs e) { }


    public virtual void ChatBotProcessValueInput(global::DirRX.ChatBotTask.Client.ChatBotProcessAssignmentChatBotProcessValueInputEventArgs e) { }


    public ChatBotProcessAssignmentClientHandlers(global::DirRX.ChatBotTask.IChatBotProcessAssignment entity) : base(entity)
    {
    }
  }

}

/// ==================================================================
/// ChatBotProcessAssignmentClientFunctions.g.cs
/// ==================================================================

namespace DirRX.ChatBotTask.Client
{
  public partial class ChatBotProcessAssignmentFunctions : global::Sungero.CoreEntities.Client.DatabookEntryFunctions
  {
    private global::DirRX.ChatBotTask.IChatBotProcessAssignment _obj
    {
      get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignment)this.Entity; }
    }

    public ChatBotProcessAssignmentFunctions(global::DirRX.ChatBotTask.IChatBotProcessAssignment entity) : base(entity) { }
  }
}

/// ==================================================================
/// ChatBotProcessAssignmentFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Functions
{
  internal static class ChatBotProcessAssignment
  {
  }
}

/// ==================================================================
/// ChatBotProcessAssignmentClientPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Client
{
  public class ChatBotProcessAssignmentClientPublicFunctions : global::DirRX.ChatBotTask.Client.IChatBotProcessAssignmentClientPublicFunctions
  {
  }
}

/// ==================================================================
/// ChatBotProcessAssignmentActions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Client
{
  public partial class ChatBotProcessAssignmentActions : global::Sungero.CoreEntities.Client.DatabookEntryActions
  {
    private global::DirRX.ChatBotTask.IChatBotProcessAssignment _obj { get { return (global::DirRX.ChatBotTask.IChatBotProcessAssignment)this.Entity; } }
    public ChatBotProcessAssignmentActions(global::DirRX.ChatBotTask.IChatBotProcessAssignment entity) : base(entity) { }
  }

  public partial class ChatBotProcessAssignmentCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::DirRX.ChatBotTask.IChatBotProcessAssignment> _objs
    { 
      get { return global::System.Linq.Enumerable.Cast<global::DirRX.ChatBotTask.IChatBotProcessAssignment>(this.Entities); }
    }
  }

  public partial class ChatBotProcessAssignmentAnyChildEntityActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityActions
  {
  }

  public partial class ChatBotProcessAssignmentAnyChildEntityCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityCollectionActions
  {
  }

}
