
/// ==================================================================
/// EmployeeState.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Shared
{
  public class EmployeeState : 
    global::Sungero.Company.Shared.EmployeeState, global::DirRX.Solution.IEmployeeState
  {
    public EmployeeState(global::DirRX.Solution.IEmployee entity) : base(entity) { }

    public new global::DirRX.Solution.IEmployeePropertyStates Properties
    {
      get { return (global::DirRX.Solution.IEmployeePropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::DirRX.Solution.Shared.EmployeePropertyStates(entity);
    }


    public new global::DirRX.Solution.IEmployeeControlStates Controls
    {
      get { return (global::DirRX.Solution.IEmployeeControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::DirRX.Solution.Shared.EmployeeControlStates(entity);
    }

  }


  public class EmployeeControlStates : 
    global::Sungero.Company.Shared.EmployeeControlStates, global::DirRX.Solution.IEmployeeControlStates
  {

    protected internal EmployeeControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class EmployeePropertyStates : 
    global::Sungero.Company.Shared.EmployeePropertyStates, global::DirRX.Solution.IEmployeePropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Boolean?> IsAllowExecuteThroughChatBot 
            {
              get { return this.GetPropertyState<global::System.Boolean?>("IsAllowExecuteThroughChatBot"); }
            }


    protected internal EmployeePropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

/// ==================================================================
/// EmployeeEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Shared
{  
}

/// ==================================================================
/// EmployeeInfo.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Shared
{
  public class EmployeeInfo : 
    global::Sungero.Company.Shared.EmployeeInfo, global::DirRX.Solution.IEmployeeInfo
  {
    public EmployeeInfo(global::System.Type entityType) : base(entityType) { }

    public new global::DirRX.Solution.IEmployeePropertiesInfo Properties
    {
      get { return (global::DirRX.Solution.IEmployeePropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::DirRX.Solution.Shared.EmployeePropertiesInfo(entityType);
    }

  }

  public class EmployeePropertiesInfo : 
    global::Sungero.Company.Shared.EmployeePropertiesInfo, global::DirRX.Solution.IEmployeePropertiesInfo
  {
        public global::Sungero.Domain.Shared.IBooleanPropertyInfo IsAllowExecuteThroughChatBot 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.BooleanPropertyMetadata>("IsAllowExecuteThroughChatBot");
             return new global::Sungero.Domain.Shared.BooleanPropertyInfo(propertyMetadata);
          }
        }


    protected internal EmployeePropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}

/// ==================================================================
/// EmployeeHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution
{
  public partial class EmployeeSharedHandlers : global::Sungero.Company.EmployeeSharedHandlers
  {
    private global::DirRX.Solution.IEmployee _obj
    {
      get { return (global::DirRX.Solution.IEmployee)this.Entity; }
    }
    public virtual void IsAllowExecuteThroughChatBotChanged(global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs e) { }




    public EmployeeSharedHandlers(global::DirRX.Solution.IEmployee entity) : base(entity)
    {
    }
  }

}

/// ==================================================================
/// EmployeeResources.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Shared.Employee
{
  /// <summary>
  /// Represents Employee resources.
  /// </summary>
  public class EmployeeResources : global::Sungero.Company.Shared.Employee.EmployeeResources, global::DirRX.Solution.Employee.IEmployeeResources
  {
  }
}

/// ==================================================================
/// EmployeeSharedFunctions.g.cs
/// ==================================================================

namespace DirRX.Solution.Shared
{
  public partial class EmployeeFunctions : global::Sungero.Company.Shared.EmployeeFunctions
  {
    private global::DirRX.Solution.IEmployee _obj
    {
      get { return (global::DirRX.Solution.IEmployee)this.Entity; }
    }

    public EmployeeFunctions(global::DirRX.Solution.IEmployee entity) : base(entity) { }
  }
}

/// ==================================================================
/// EmployeeFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Functions
{
  internal static class Employee
  {
  }
}

/// ==================================================================
/// EmployeeFilterState.g.cs
/// ==================================================================

namespace DirRX.Solution.Shared.Employee
{
  public class EmployeeFilterState : global::Sungero.Company.Shared.Employee.EmployeeFilterState,
    global::DirRX.Solution.IEmployeeFilterState
  {


  }
}

/// ==================================================================
/// EmployeeSharedPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Shared
{
  public class EmployeeSharedPublicFunctions : global::DirRX.Solution.Shared.IEmployeeSharedPublicFunctions
  {
  }
}
