
/// ==================================================================
/// EmployeeEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Client
{ 
}

/// ==================================================================
/// EmployeeHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution
{
  public partial class EmployeeClientHandlers : global::Sungero.Company.EmployeeClientHandlers
  {
    private global::DirRX.Solution.IEmployee _obj
    {
      get { return (global::DirRX.Solution.IEmployee)this.Entity; }
    }

    public virtual void IsAllowExecuteThroughChatBotValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public EmployeeClientHandlers(global::DirRX.Solution.IEmployee entity) : base(entity)
    {
    }
  }

}

/// ==================================================================
/// EmployeeClientFunctions.g.cs
/// ==================================================================

namespace DirRX.Solution.Client
{
  public partial class EmployeeFunctions : global::Sungero.Company.Client.EmployeeFunctions
  {
    private global::DirRX.Solution.IEmployee _obj
    {
      get { return (global::DirRX.Solution.IEmployee)this.Entity; }
    }

    public EmployeeFunctions(global::DirRX.Solution.IEmployee entity) : base(entity) { }
  }
}

/// ==================================================================
/// EmployeeFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Functions
{
  internal static class Employee
  {
  }
}

/// ==================================================================
/// EmployeeClientPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Client
{
  public class EmployeeClientPublicFunctions : global::DirRX.Solution.Client.IEmployeeClientPublicFunctions
  {
  }
}

/// ==================================================================
/// EmployeeActions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Client
{
  public partial class EmployeeActions : global::Sungero.Company.Client.EmployeeActions
  {
    private global::DirRX.Solution.IEmployee _obj { get { return (global::DirRX.Solution.IEmployee)this.Entity; } }
    public EmployeeActions(global::DirRX.Solution.IEmployee entity) : base(entity) { }
  }

  public partial class EmployeeCollectionActions : global::Sungero.Company.Client.EmployeeCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::DirRX.Solution.IEmployee> _objs
    { 
      get { return global::System.Linq.Enumerable.Cast<global::DirRX.Solution.IEmployee>(this.Entities); }
    }
  }

  public partial class EmployeeAnyChildEntityActions : global::Sungero.Company.Client.EmployeeAnyChildEntityActions
  {
  }

  public partial class EmployeeAnyChildEntityCollectionActions : global::Sungero.Company.Client.EmployeeAnyChildEntityCollectionActions
  {
  }

}
