//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Client
{
  /// <summary>
  /// Interaction logic for ChatBotProcessAssignmentCollectionView.xaml.
  /// </summary>
  public partial class ChatBotProcessAssignmentCollectionView : global::System.Windows.Controls.UserControl
  {
    public ChatBotProcessAssignmentCollectionView()
    {
      InitializeComponent();
    }
  }
}