
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Server
{
  public partial class SolutionModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("e77dcf96-3448-4bf6-a3d0-82a64033f6e1"); }
    }

    public override string Name
    {
      get { return "DirRX.Solution"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("7dc35907-1ed5-4ae7-bb1e-1ff8315f1e69"), new DirRX.Solution.Shared.EmployeeInfo(typeof(global::DirRX.Solution.IEmployee)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Server.IEmployeeServerPublicFunctions, global::DirRX.Solution.Server.EmployeeServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Shared.IEmployeeSharedPublicFunctions, global::DirRX.Solution.Shared.EmployeeSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.IEmployeeFilterState, global::DirRX.Solution.Shared.Employee.EmployeeFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.ChatBotInfrastructurePI.Server.IModuleServerPublicFunctions, global::DirRX.Solution.Module.ChatBotInfrastructurePI.Server.ModuleServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.ChatBotInfrastructurePI.Shared.IModuleSharedPublicFunctions, global::DirRX.Solution.Module.ChatBotInfrastructurePI.Shared.ModuleSharedPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.Company.Server.IModuleServerPublicFunctions, global::DirRX.Solution.Module.Company.Server.ModuleServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.Company.Shared.IModuleSharedPublicFunctions, global::DirRX.Solution.Module.Company.Shared.ModuleSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Server.IModuleServerPublicFunctions, global::DirRX.Solution.Server.ModuleServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Shared.IModuleSharedPublicFunctions, global::DirRX.Solution.Shared.ModuleSharedPublicFunctions>();
    }
  }
}

/// ==================================================================
/// ModuleHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Server
{
}

/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Functions
{
  internal static partial class Module
  {
    private static object GetFunctionsContainer()
    {
      return new global::DirRX.Solution.Server.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("e77dcf96-3448-4bf6-a3d0-82a64033f6e1");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}

/// ==================================================================
/// ModuleInitializationInstantiation.g.cs
/// ==================================================================



/// ==================================================================
/// ModuleEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Server
{
}

/// ==================================================================
/// ModuleServerPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Server
{
  public partial class ModuleServerPublicFunctions : global::DirRX.Solution.Server.IModuleServerPublicFunctions
  {
  }
}

namespace DirRX.Solution.Server
{
  public partial class ModuleServerPublicFunctions : global::DirRX.Solution.Server.IModuleServerPublicFunctions
  {
  }
}

/// ==================================================================
/// ModuleServerInitializationFunctions.g.cs
/// ==================================================================



/// ==================================================================
/// ModuleWidgetHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Server
{
}

/// ==================================================================
/// ModuleQueries.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Queries
{
  public class Module
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("DirRX.Solution.Server.ModuleQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}

/// ==================================================================
/// ModuleInitializer.g.cs
/// ==================================================================


