
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
  public partial class ChatBotTaskModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717"); }
    }

    public override string Name
    {
      get { return "DirRX.ChatBotTask"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.ChatBotTask.Server.IModuleServerInitializationFunctions, global::DirRX.ChatBotTask.Server.ModuleServerInitializationFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("eef6834c-36a0-490f-8d7b-4962162f9890"), new DirRX.ChatBotTask.Shared.ChatBotProcessAssignmentInfo(typeof(global::DirRX.ChatBotTask.IChatBotProcessAssignment)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.ChatBotTask.Server.IChatBotProcessAssignmentServerPublicFunctions, global::DirRX.ChatBotTask.Server.ChatBotProcessAssignmentServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.ChatBotTask.Shared.IChatBotProcessAssignmentSharedPublicFunctions, global::DirRX.ChatBotTask.Shared.ChatBotProcessAssignmentSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.ChatBotTask.IChatBotProcessAssignmentFilterState, global::DirRX.ChatBotTask.Shared.ChatBotProcessAssignment.ChatBotProcessAssignmentFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.ChatBotTask.Server.IModuleServerPublicFunctions, global::DirRX.ChatBotTask.Server.ModuleServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.ChatBotTask.Shared.IModuleSharedPublicFunctions, global::DirRX.ChatBotTask.Shared.ModuleSharedPublicFunctions>();
    }
  }
}

/// ==================================================================
/// ModuleHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
}

/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Functions
{
  internal static partial class Module
  {
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static void SendNotification()
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).SendNotification();
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static global::System.DateTime GetLastNotificationDate()
    {
        return global::DirRX.ChatBotTask.Server.ModuleFunctions.GetLastNotificationDate();
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void UpdateLastNotificationDate(global::System.DateTime notificationDate)
    {
    global::DirRX.ChatBotTask.Server.ModuleFunctions.UpdateLastNotificationDate(notificationDate);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static global::System.Boolean CheckAssignmentType(global::System.String typeName)
    {
        return ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).CheckAssignmentType(typeName);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void TrySendNewAssignmentsToChatBot(global::System.DateTime previousRun, global::System.DateTime notificationDate)
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).TrySendNewAssignmentsToChatBot(previousRun, notificationDate);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void TrySendAssignmentMessage(global::Sungero.Workflow.IAssignment assignment)
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).TrySendAssignmentMessage(assignment);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void SendAssignmentMessage(global::Sungero.Workflow.IAssignment assignment, global::DirRX.ChatBotInfrastructure.IChatBotUser chatBotUser)
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).SendAssignmentMessage(assignment, chatBotUser);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static global::Sungero.Content.IElectronicDocument[] GetAttachements(global::Sungero.Workflow.IAssignmentBase assignment)
    {
        return ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).GetAttachements(assignment);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static global::DirRX.ChatBotTask.Structures.Module.ChatBotProcessAssignmentType GetChatBotProcessAssignmentType(global::Sungero.Workflow.IAssignmentBase assignment)
    {
        return ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).GetChatBotProcessAssignmentType(assignment);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void ReceiveJob(global::DirRX.ChatBotInfrastructure.IChatJob chatJob)
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).ReceiveJob(chatJob);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void ProcessAssignment(global::DirRX.ChatBotInfrastructure.IChatJob chatJob)
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).ProcessAssignment(chatJob);
    }
    /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
    internal static void CompleteAssigment(global::Sungero.Workflow.IAssignment assignment, global::System.String assignmentResult, global::System.String activeText)
    {
    ((global::DirRX.ChatBotTask.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server)).CompleteAssigment(assignment, assignmentResult, activeText);
    }

    private static object GetFunctionsContainer()
    {
      return new global::DirRX.ChatBotTask.Server.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("b48729d6-1056-4320-b51a-ffc0e085c717");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}

/// ==================================================================
/// ModuleInitializationInstantiation.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.ModuleInitialization
{
  internal static partial class Module
  {

    private static object GetFunctionsContainer()
    {
      return new global::DirRX.ChatBotTask.Server.ModuleInitializer();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("b48729d6-1056-4320-b51a-ffc0e085c717");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.ModuleInitializationNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }

  }
}


/// ==================================================================
/// ModuleEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
}

/// ==================================================================
/// ModuleServerPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
  public partial class ModuleServerPublicFunctions : global::DirRX.ChatBotTask.Server.IModuleServerPublicFunctions
  {
    public void ReceiveJob(global::DirRX.ChatBotInfrastructure.IChatJob chatJob)
    {
global::DirRX.ChatBotTask.Functions.Module.ReceiveJob(chatJob);
    }
    public void SendAssignmentMessage(global::Sungero.Workflow.IAssignment assignment, global::DirRX.ChatBotInfrastructure.IChatBotUser chatBotUser)
    {
global::DirRX.ChatBotTask.Functions.Module.SendAssignmentMessage(assignment, chatBotUser);
    }
    public void TrySendAssignmentMessage(global::Sungero.Workflow.IAssignment assignment)
    {
global::DirRX.ChatBotTask.Functions.Module.TrySendAssignmentMessage(assignment);
    }
    public void TrySendNewAssignmentsToChatBot(global::System.DateTime previousRun, global::System.DateTime notificationDate)
    {
global::DirRX.ChatBotTask.Functions.Module.TrySendNewAssignmentsToChatBot(previousRun, notificationDate);
    }
    public void UpdateLastNotificationDate(global::System.DateTime notificationDate)
    {
global::DirRX.ChatBotTask.Functions.Module.UpdateLastNotificationDate(notificationDate);
    }
  }
}

namespace DirRX.ChatBotTask.Server
{
  public partial class ModuleServerPublicFunctions : global::DirRX.ChatBotTask.Server.IModuleServerPublicFunctions
  {
      private static readonly global::System.Guid JobSendChatBotNotificationId = global::System.Guid.Parse("b0402ed3-1279-470f-bb4a-4299ea7d2c4e");

      public void Enqueue_SendChatBotNotification()
      {      
         global::Sungero.Agent.JobsManager.Enqueue(JobSendChatBotNotificationId, null);
      }
 

  }
}

/// ==================================================================
/// ModuleServerInitializationFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
  public partial class ModuleServerInitializationFunctions : global::DirRX.ChatBotTask.Server.IModuleServerInitializationFunctions
  {
  }
}


/// ==================================================================
/// ModuleWidgetHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
}

/// ==================================================================
/// ModuleQueries.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Queries
{
  public class Module
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("DirRX.ChatBotTask.Server.ModuleQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
    public static string SelectDocflowParamsValue
    {
       get { return resolver.GetQuery("SelectDocflowParamsValue"); }
    }
    public static string InsertOrUpdateDocflowParamsValue
    {
       get { return resolver.GetQuery("InsertOrUpdateDocflowParamsValue"); }
    }
  }
}

/// ==================================================================
/// ModuleInitializer.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Server
{
  public partial class ModuleInitializer : global::Sungero.Domain.AppliedModuleInitializer
  {
  }
}

