
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.Solution.Client
{
  public partial class SolutionModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("e77dcf96-3448-4bf6-a3d0-82a64033f6e1"); }
    }

    public override string Name
    {
      get { return "DirRX.Solution"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("7dc35907-1ed5-4ae7-bb1e-1ff8315f1e69"), new DirRX.Solution.Shared.EmployeeInfo(typeof(global::DirRX.Solution.IEmployee)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Client.IEmployeeClientPublicFunctions, global::DirRX.Solution.Client.EmployeeClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Shared.IEmployeeSharedPublicFunctions, global::DirRX.Solution.Shared.EmployeeSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.IEmployeeFilterState, global::DirRX.Solution.Shared.Employee.EmployeeFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.ChatBotInfrastructurePI.Client.IModuleClientPublicFunctions, global::DirRX.Solution.Module.ChatBotInfrastructurePI.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.ChatBotInfrastructurePI.Shared.IModuleSharedPublicFunctions, global::DirRX.Solution.Module.ChatBotInfrastructurePI.Shared.ModuleSharedPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.Company.Client.IModuleClientPublicFunctions, global::DirRX.Solution.Module.Company.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Module.Company.Shared.IModuleSharedPublicFunctions, global::DirRX.Solution.Module.Company.Shared.ModuleSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Client.IModuleClientPublicFunctions, global::DirRX.Solution.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::DirRX.Solution.Shared.IModuleSharedPublicFunctions, global::DirRX.Solution.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
