
/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Functions
{
  internal static partial class Module
  {
    internal static class Remote
    {
      /// <redirect project="DirRX.ChatBotTask.Server" type="DirRX.ChatBotTask.Server.ModuleFunctions" />
      internal static void SendNotification()
      {
      global::Sungero.Domain.Shared.RemoteFunctionExecutor.Execute(
          global::System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717"),
          "SendNotification()");
      }

    }
    private static object GetFunctionsContainer()
    {
      return new global::DirRX.ChatBotTask.Shared.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("b48729d6-1056-4320-b51a-ffc0e085c717");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}

/// ==================================================================
/// ModuleHyperlinks.g.cs
/// ==================================================================

namespace DirRX.ChatBotTask
{
  public static class ChatBotTaskClientFunctionHyperlinksExtensions
  {
  }
}

/// ==================================================================
/// ModuleResources.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{
  public class ModuleResources : global::DirRX.ChatBotTask.IModuleResources
  {
    public virtual global::CommonLibrary.LocalizedString IncomingInstructionTextSimpleAssignment
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")) , "IncomingInstructionTextSimpleAssignment", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString IncomingInstructionTextSimpleAssignmentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")), "IncomingInstructionTextSimpleAssignment", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString IncomingInstructionTextAcquaintanceAssignment
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")) , "IncomingInstructionTextAcquaintanceAssignment", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString IncomingInstructionTextAcquaintanceAssignmentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")), "IncomingInstructionTextAcquaintanceAssignment", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AssignmentText
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")) , "AssignmentText", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString AssignmentTextFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")), "AssignmentText", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString AcquaintanceAssignmentAcquaintanedText
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")) , "AcquaintanceAssignmentAcquaintanedText", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString AcquaintanceAssignmentAcquaintanedTextFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")), "AcquaintanceAssignmentAcquaintanedText", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString SimpleAssignmentCompleteText
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")) , "SimpleAssignmentCompleteText", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString SimpleAssignmentCompleteTextFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("b48729d6-1056-4320-b51a-ffc0e085c717")), "SimpleAssignmentCompleteText", false, args);
    }

  }
}

/// ==================================================================
/// ModuleFoldersFilterStates.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{
}

/// ==================================================================
/// ModuleSharedPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{
  public partial class ModuleSharedPublicFunctions : global::DirRX.ChatBotTask.Shared.IModuleSharedPublicFunctions
  {
    public void Remote_SendNotification()
    {
global::DirRX.ChatBotTask.Functions.Module.Remote.SendNotification();
    }
  }
}

/// ==================================================================
/// ModuleWidgetParameters.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirRX.ChatBotTask.Shared
{  
}
